CREATE TABLE [Usuarios](
	[UsuarioId] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioNome] [varchar](60) NOT NULL,
	[Email] [varchar](60) NOT NULL,
	[Senha] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UsuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]